"""optimize chat tables with composite timelines, native role enums, selectin relations, and unique index guards

Revision ID: 6ec4dfad7ecc
Revises: f574244834b3
Create Date: 2026-06-15 18:38:00.034413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec4dfad7ecc'
down_revision: Union[str, Sequence[str], None] = 'f574244834b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
